name: MainTests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Выберите тест
        required: true
        type: choice
        options:
          - min
          - max
          - sum
          - mult
          - read_file

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Test 
        if: "github.event.inputs.deployment_target == 'All'"
        run: mvn clean test -Dtest=org.example.MainTest
      # - name: Test max
      #   if: "github.event.inputs.deployment_target == 'max'"
      #   run: mvn clean test -Dtest=org.example.MainTestCorrectWorkTests.testMaxWork
      # - name: Test sum
      #   if: "github.event.inputs.deployment_target == 'sum'"
      #   run: mvn clean test -Dtest=org.example.CorrectWorkTests.testSumWork
      # - name: Test mult
      #   if: "github.event.inputs.deployment_target == 'mult'"
      #   run: mvn clean test -Dtest=org.example.CorrectWorkTests.testMultWork
